---

- name: "Ensure mylvmbackup is installed"
  apt: pkg=mylvmbackup state=present

- name: "Ensure packages are installed"
  apt: pkg={{ item }} state=present
  with_items:
    - libmime-lite-perl
    - libfile-copy-recursive-perl
    - libsys-syslog-perl

